### ISSUE TITLE
Can't add a source or sign in

### ISSUE THREAD

**Issue by evanzummeren** [PlanBCode/koppelbot#9]
I'm running into issues of actually adding something. If I click on the button, nothing happens. I assume that I first have to login to do so, but logging in by using the credentials in ```account.json``` don't seem to work. It's currently giving me: "Failed to create: Forbidden"

**Comment by RoukePouw** [comment]
The passwords in account.json are hashed to ensure no plain text password are stored. 
`admin admin` and `member member` are the current test values
